import os
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from app.core.config import settings

logger = logging.getLogger("historian")

class EmailServiceNotConfiguredError(Exception):
    """Raised when SMTP server parameters or credentials are missing."""
    pass

class SMTPDeliveryError(Exception):
    """Raised when SMTP server rejects or fails during transmission."""
    pass

def mask_email(email: str) -> str:
    """Mask email for privacy display (e.g. v***v@example.com)"""
    if not email or "@" not in email:
        return email
    user, domain = email.split("@", 1)
    if len(user) <= 2:
        masked_user = user[0] + "*"
    else:
        masked_user = user[0] + "*" * (len(user) - 2) + user[-1]
    return f"{masked_user}@{domain}"

def send_employee_result_email(recipient_email: str, employee: dict, search_method: str = "Employee Badge/Image → OCR → Employee Directory", user_role: str = "Enterprise Executive"):
    """
    Generates and dispatches a professionally formatted enterprise HTML/Text email 
    containing the Historian AI Employee Search Result directly to the user's inbox via SMTP.
    """
    if not recipient_email or "@" not in recipient_email:
        raise ValueError("Invalid recipient email address.")

    if not employee or "employee_id" not in employee:
        raise ValueError("Invalid employee profile data.")

    emp_id = employee.get("employee_id", "N/A")
    emp_name = employee.get("name", "N/A")
    designation = employee.get("designation", "N/A")
    department = employee.get("department", "N/A")
    work_email = employee.get("email", "N/A")
    joining_date = employee.get("joining_date", "N/A")
    location = employee.get("location", "N/A")
    manager = employee.get("manager", "N/A")
    status = employee.get("employment_status", "Active • Full-Time")
    security_clearance = employee.get("security_clearance", "Level 4 - Confidential")

    # Historian System Analytics (Included if authorized)
    metrics = employee.get("historian_metrics") or {}
    perf_score = metrics.get("performance_score", 94.0)
    attendance = metrics.get("attendance_rate", "95.0%")
    risk_level = metrics.get("risk_classification", "Low Risk")

    subject = f"Historian AI — Employee Search Result ({emp_name} - {emp_id})"

    # Plain text body fallback
    text_content = f"""
=====================================================
HISTORIAN AI — EMPLOYEE SEARCH RESULT
=====================================================

Employee Profile Found:
-----------------------------------------------------
Name: {emp_name}
Employee ID: {emp_id}
Designation: {designation}
Department: {department}
Work Email: {work_email}
Joining Date: {joining_date}
Location: {location}
Reporting Manager: {manager}
Employment Status: {status}
Security Clearance: {security_clearance}

Historian Performance Analytics:
-----------------------------------------------------
Performance Index: {perf_score}%
Attendance Rate: {attendance}
Risk Assessment: {risk_level}

Search Provenance:
-----------------------------------------------------
Method: {search_method}
Dispatched At: {datetime.now().strftime('%B %d, %Y at %H:%M:%S UTC')}
Authorized Recipient: {recipient_email}

=====================================================
Confidential Enterprise Report • Generated by Historian AI
"Enterprise Memory. Intelligent Decisions."
    """.strip()

    # HTML body matching Historian enterprise design language (#F9F4BC, #FF8000, #1F2937)
    html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{subject}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #F9F4BC; font-family: 'Segoe UI', Arial, sans-serif; color: #1F2937;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color: #F9F4BC; padding: 24px 0;">
        <tr>
            <td align="center">
                <table role="presentation" width="600" cellspacing="0" cellpadding="0" style="background-color: #FFFFFF; border-radius: 16px; overflow: hidden; border: 1px solid #E8E4D0; box-shadow: 0 4px 16px rgba(0,0,0,0.06);">
                    <!-- Header -->
                    <tr>
                        <td style="background-color: #1F2937; padding: 24px; text-align: left; border-bottom: 3px solid #FF8000;">
                            <table width="100%" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td>
                                        <h1 style="color: #FFFFFF; font-size: 20px; font-weight: 800; margin: 0; letter-spacing: -0.5px;">Historian AI</h1>
                                        <p style="color: #FF8000; font-size: 12px; font-weight: 700; margin: 4px 0 0 0; text-transform: uppercase; letter-spacing: 1px;">Enterprise Memory & Intelligence Result</p>
                                    </td>
                                    <td align="right">
                                        <span style="background-color: #FF8000; color: #FFFFFF; font-size: 10px; font-weight: 800; padding: 4px 10px; border-radius: 6px; text-transform: uppercase;">VERIFIED</span>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <!-- Body -->
                    <tr>
                        <td style="padding: 28px;">
                            <h2 style="font-size: 18px; font-weight: 800; color: #1F2937; margin: 0 0 8px 0;">Employee Search Result</h2>
                            <p style="font-size: 13px; color: #6B7280; margin: 0 0 24px 0; font-weight: 500;">
                                Below are the authorized directory details retrieved for the requested employee.
                            </p>

                            <!-- Profile Highlight Card -->
                            <table width="100%" cellspacing="0" cellpadding="0" style="background-color: #FFFDF7; border: 1px solid #FFD1A4; border-radius: 12px; padding: 20px; margin-bottom: 24px;">
                                <tr>
                                    <td>
                                        <table width="100%" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td>
                                                    <h3 style="font-size: 16px; font-weight: 800; color: #1F2937; margin: 0;">{emp_name}</h3>
                                                    <p style="font-size: 12px; font-weight: 700; color: #FF8000; margin: 2px 0 0 0;">{designation}</p>
                                                </td>
                                                <td align="right">
                                                    <span style="background-color: #1F2937; color: #FFFFFF; font-size: 11px; font-weight: 800; padding: 4px 8px; border-radius: 6px;">{emp_id}</span>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>

                            <!-- Details Table -->
                            <table width="100%" cellspacing="0" cellpadding="0" style="font-size: 12px; margin-bottom: 24px;">
                                <tr>
                                    <td width="50%" style="padding: 8px 0; border-bottom: 1px solid #F3F4F6;">
                                        <span style="color: #9CA3AF; font-weight: 700;">Department:</span><br>
                                        <strong style="color: #1F2937; font-size: 13px;">{department}</strong>
                                    </td>
                                    <td width="50%" style="padding: 8px 0; border-bottom: 1px solid #F3F4F6;">
                                        <span style="color: #9CA3AF; font-weight: 700;">Work Email:</span><br>
                                        <strong style="color: #1F2937; font-size: 13px;">{work_email}</strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="50%" style="padding: 8px 0; border-bottom: 1px solid #F3F4F6;">
                                        <span style="color: #9CA3AF; font-weight: 700;">Joining Date:</span><br>
                                        <strong style="color: #1F2937; font-size: 13px;">{joining_date}</strong>
                                    </td>
                                    <td width="50%" style="padding: 8px 0; border-bottom: 1px solid #F3F4F6;">
                                        <span style="color: #9CA3AF; font-weight: 700;">Location:</span><br>
                                        <strong style="color: #1F2937; font-size: 13px;">{location}</strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="50%" style="padding: 8px 0; border-bottom: 1px solid #F3F4F6;">
                                        <span style="color: #9CA3AF; font-weight: 700;">Reporting Manager:</span><br>
                                        <strong style="color: #1F2937; font-size: 13px;">{manager}</strong>
                                    </td>
                                    <td width="50%" style="padding: 8px 0; border-bottom: 1px solid #F3F4F6;">
                                        <span style="color: #9CA3AF; font-weight: 700;">Status:</span><br>
                                        <strong style="color: #059669; font-size: 13px;">{status}</strong>
                                    </td>
                                </tr>
                            </table>

                            <!-- Analytics Summary -->
                            <table width="100%" cellspacing="0" cellpadding="0" style="background-color: #F9FAFB; border: 1px solid #E5E7EB; border-radius: 12px; padding: 16px; margin-bottom: 24px;">
                                <tr>
                                    <td style="font-size: 11px; font-weight: 800; color: #1F2937; text-transform: uppercase; padding-bottom: 8px;">Historian System Analytics</td>
                                </tr>
                                <tr>
                                    <td>
                                        <table width="100%" cellspacing="0" cellpadding="0" style="font-size: 12px; text-align: center;">
                                            <tr>
                                                <td width="33%" style="padding: 8px; background-color: #FFFFFF; border-radius: 8px; border: 1px solid #E5E7EB;">
                                                    <span style="color: #6B7280; font-size: 10px; font-weight: 700;">Performance</span><br>
                                                    <strong style="font-size: 15px; color: #1F2937;">{perf_score}%</strong>
                                                </td>
                                                <td width="33%" style="padding: 8px; background-color: #FFFFFF; border-radius: 8px; border: 1px solid #E5E7EB;">
                                                    <span style="color: #6B7280; font-size: 10px; font-weight: 700;">Attendance</span><br>
                                                    <strong style="font-size: 15px; color: #FF8000;">{attendance}</strong>
                                                </td>
                                                <td width="33%" style="padding: 8px; background-color: #FFFFFF; border-radius: 8px; border: 1px solid #E5E7EB;">
                                                    <span style="color: #6B7280; font-size: 10px; font-weight: 700;">Risk Level</span><br>
                                                    <strong style="font-size: 15px; color: #059669;">{risk_level}</strong>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>

                            <!-- Audit Information -->
                            <p style="font-size: 11px; color: #9CA3AF; margin: 0; line-height: 1.5;">
                                <strong>Search Provenance:</strong> {search_method}<br>
                                <strong>Dispatched To Registered User:</strong> {recipient_email}<br>
                                <strong>Security Clearance:</strong> {security_clearance}
                            </p>
                        </td>
                    </tr>

                    <!-- Footer -->
                    <tr>
                        <td style="background-color: #F9FAFB; padding: 16px 24px; text-align: center; border-top: 1px solid #E5E7EB; font-size: 11px; color: #6B7280;">
                            Historian Enterprise Intelligence Engine • Confidential Document<br>
                            This result was requested by authenticated user <strong>{recipient_email}</strong>.
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
    """.strip()

    # Read SMTP Configuration from server-side environment variables
    smtp_host = (settings.SMTP_HOST or os.getenv("SMTP_HOST", "")).strip()
    smtp_port = int(settings.SMTP_PORT or os.getenv("SMTP_PORT", "587"))
    smtp_user = (settings.SMTP_USER or os.getenv("SMTP_USER", "")).strip()
    smtp_pass = (settings.SMTP_PASSWORD or os.getenv("SMTP_PASSWORD", "")).strip()

    # 1. Enforce SMTP Credentials Configuration
    if not smtp_host or not smtp_user or not smtp_pass:
        logger.warning(f"[EMAIL UNCONFIGURED] Attempted to send email to {recipient_email} for employee {emp_id}, but SMTP settings are missing in backend/.env.")
        raise EmailServiceNotConfiguredError("Email service is not configured. Please configure SMTP settings.")

    # 2. Attempt Real SMTP Transmission
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        from_email = settings.EMAILS_FROM_EMAIL or smtp_user
        from_name = settings.EMAILS_FROM_NAME or "Historian AI"
        msg["From"] = f"{from_name} <{from_email}>"
        msg["To"] = recipient_email

        msg.attach(MIMEText(text_content, "plain"))
        msg.attach(MIMEText(html_content, "html"))

        with smtplib.SMTP(smtp_host, smtp_port, timeout=12) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_user, smtp_pass)
            server.sendmail(from_email, [recipient_email], msg.as_string())

        logger.info(f"[AUDIT LOG] Real SMTP email delivered to {recipient_email} for employee {emp_id}")
        return {
            "success": True,
            "recipient": recipient_email,
            "employee_id": emp_id,
            "mode": "smtp",
            "message": f"Result sent successfully to your registered email."
        }
    except Exception as e:
        logger.error(f"[SMTP DELIVERY ERROR] Failed to send email to {recipient_email}: {type(e).__name__}")
        raise SMTPDeliveryError("Unable to send the result email. Please try again.")
